{% set name = "nbparameterise" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bbdc59c1a3af4071479d34b184374874ae937256cb72be54ecf4f73494355dd4

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3.2,<4
  run:
    - python >={{ python_min }}
    - nbconvert
    - astcheck >=0.3

test:
  requires:
    - python {{ python_min }}
  imports:
    - nbparameterise

about:
  home: https://github.com/takluyver/nbparameterise
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This is a tool to run notebooks with input values.
  doc_url: https://github.com/takluyver/nbparameterise
  dev_url: https://github.com/takluyver/nbparameterise

extra:
  recipe-maintainers:
    - kmuehlbauer
